server:
  #port: ${PORT:0}
  port: 8081
  servlet:
    context-path: /infaauthorizationserver

spring:
  application:
    name: infa-authserver
  main:
    allow-circular-references: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
infa:
  jwt:
    secret: InF4Br4$Il
    expiration: 86400000
